// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: broker.proto

package broker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Broker_Kaho_FullMethodName = "/Broker/Kaho"
	Broker_Suno_FullMethodName = "/Broker/Suno"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	Kaho(ctx context.Context, in *KahoRequest, opts ...grpc.CallOption) (*Baat, error)
	Suno(ctx context.Context, in *SunoRequest, opts ...grpc.CallOption) (Broker_SunoClient, error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) Kaho(ctx context.Context, in *KahoRequest, opts ...grpc.CallOption) (*Baat, error) {
	out := new(Baat)
	err := c.cc.Invoke(ctx, Broker_Kaho_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Suno(ctx context.Context, in *SunoRequest, opts ...grpc.CallOption) (Broker_SunoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Broker_ServiceDesc.Streams[0], Broker_Suno_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerSunoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_SunoClient interface {
	Recv() (*Baat, error)
	grpc.ClientStream
}

type brokerSunoClient struct {
	grpc.ClientStream
}

func (x *brokerSunoClient) Recv() (*Baat, error) {
	m := new(Baat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility
type BrokerServer interface {
	Kaho(context.Context, *KahoRequest) (*Baat, error)
	Suno(*SunoRequest, Broker_SunoServer) error
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (UnimplementedBrokerServer) Kaho(context.Context, *KahoRequest) (*Baat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kaho not implemented")
}
func (UnimplementedBrokerServer) Suno(*SunoRequest, Broker_SunoServer) error {
	return status.Errorf(codes.Unimplemented, "method Suno not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_Kaho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KahoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Kaho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_Kaho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Kaho(ctx, req.(*KahoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Suno_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SunoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).Suno(m, &brokerSunoServer{stream})
}

type Broker_SunoServer interface {
	Send(*Baat) error
	grpc.ServerStream
}

type brokerSunoServer struct {
	grpc.ServerStream
}

func (x *brokerSunoServer) Send(m *Baat) error {
	return x.ServerStream.SendMsg(m)
}

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kaho",
			Handler:    _Broker_Kaho_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Suno",
			Handler:       _Broker_Suno_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "broker.proto",
}
